# version: "3.9"

services:
  backend:
    build: ./server
    container_name: chat-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat-app
      - DEMO_VAR=vishal_vishwas
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: chat-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: chat-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  postgres:
    image: postgres:15
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_logs
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  pg_data: